# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Wei Yang
title: Data Science candidate at Stevens
email: wyang17@stevens.edu
# email_title: Email (Email title override)
phone: +1 551 260 0541
# phone_title: Phone (Phone title override)
website: https://inscribedeeper.github.io/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username: inscribedeeper
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: weiyangds
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/wyang_img.jpg # Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
    I am a recent graduate in the data science program who is equipped with a solid understanding of machine learning algorithms and python programming experience. I also am a person really enjoys solving technically challenging problems. Eagerness to solve and passion to summarize the understanding from this process enables me to have an in-depth understanding of whatever I touch. 

    I already got my EAD card and my OPT will start on Feb 14, 2022. I will be really glad to show my passion if there is a possible conversation with you.

    - Stacks:
        - Programming Language: Python, SQL, R, JavaScript, Shell Script
        - Database: MongoDB, PostgreSQL, MySQL, SQL Server
        - Tools: Git, AWS, Jupyter Notebook, Google Colab
        - Operating Systems: Windows, UNIX/Linux, Mac OS X

    - Python related packages:
        - Data Manupulation: Pandas, Numpy, Regular Expression
        - Textual Data Processing: SpaCy, NLTK, Gensim
        - Machine Learning and Deep Learning: Pytorch, HuggingFace Transformers, Scikit-Learn, Keras
        - Data Visualization: Matplotlib, Seaborn, Tableau

    - Algorithms/Models:
        - Regression: Linear Regression, Hinge/Lasso Regression, Time series regression (ARIMA)
        - Classification: Support Vector Machine, Logistic Regression, Naive Bayes, Decision Tree, K-nearest Neighbors (KNN)
        - Dimension Reduction: Principal Component Analysis (PCA), Singular Value Decomposition (SVD)
        - Clustering: K-means, Hierarchical Clustering, DBSCAN
        - Emsembling techniques: Bagging, Boosting, Stacking
        - Neural Networks: Recurrent Neural Networks (LSTM), Convolutional Neural Networks, Variational Autoencoder, 
        - NLP: Word2Vector, BERT, Transformer, Latent Dirichlet Allocation

# Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

# You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#   - Lists
#   - Tables
#   - <a href="google.com">Links</a>
#   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
    - title: Experience
      layout: list
      content:
          - layout: left
            title: Stevens Institute of Technology
            sub_title: Research Assistant/Teaching Assistant, Deep Learning and Web Analytics
            caption: June 2020 - December 2021
            link: https://github.com/InscribeDeeper/Conf_Call
            link_text: InscribeDeeper/Conf_Call
            quote: >
                Focusing on language features pattern detection, data parsing and modeling.
            description: | # this will include new lines to allow paragraphs
                - Parsed and structured 94,581 earnings call transcripts to explore factors influencing stock return 
                - Measured sentence coherence based on POS-tagging, NER, and coreference resolution with SpaCy 
                - Achieved 72% accuracy with Fine-tuned domain adapted BERT language model for text classification 
                - Performed univariate features selection and panel regression on 96 extracted language features
                - Offered after-school academic support to 3 students; partnered with a PhD student to guild 40 students on python related OS environment and packages setup; delivered tutorials of Pandas, NumPy, and related packages to implement deep learning models

          - layout: left
            title: Stevens Institute of Technology
            sub_title: Data Scientist Intern on Condo Book Data Collection
            caption: June 2020 - December 2021
            quote: >
                Focusing on data scraping, parsing and modeling.
            description: | # this will include new lines to allow paragraphs
                - Scraped public real estate and taxation data from NYC.gov with Selenium and BeautifulSoup 
                - Proposed OCR, NLP, and machine learning solutions to automate manual data collection processes 
                - Achieved 90% straight-through processing by designed pipeline to tabulate data from scanned PDFs 
                - Standardized 3,023 table headers for data integration with clustering algorithms and rule-based methods

          - layout: left
            title: 1lift
            sub_title: Data Analyst Intern
            caption: April 2019 - July 2019
            quote: >
                Gained hands-on experience on necessary tools
            description: | # this will include new lines to allow paragraphs
                - Built a cost analysis module for the application with Excel advanced functionalities
                - Extracted structured data with MySQL, cleaned the unstructured textual data with Python
                - Manipulated, visualized and presented the statistical results with Tableau Dashboard
                - Explored regression models to provide a baseline of elevators' failure rate for the Operations Department

    - title: Projects # Title for the section
      layout: list # Type of content section (list/text)
      content:
          - layout: right
            title: Quantify the AI impacts on Jobs skills
            link: https://github.com/InscribeDeeper/Job-Descrpition-Feature-extraction
            link_text: InscribeDeeper/Job-Descrpition-Feature-extraction
            additional_links:
                - title: InscribeDeeper/Job-Descrpition-Feature-extraction
                  icon: fab fa-github
                  url: https://github.com/InscribeDeeper/Job-Descrpition-Feature-extraction
            quote: >
                Develop a web application for furniture and rental information exchange
            description: | # this will include new lines to allow paragraphs
                - Led team of four students to design and develop a web application with Node.js and Express 
                - Designed document schema on MongoDB and wrapped CRUD operations as RESTful APIs 
                - Implemented Login and user-specific functions such as account signup and authentication system 
                - Developed features for rental and furniture information exchange such as comments, search, dashboard

          - layout: right
            title: Quantify the AI impacts on Jobs skills
            link: https://github.com/InscribeDeeper/Job-Descrpition-Feature-extraction
            link_text: InscribeDeeper/Job-Descrpition-Feature-extraction
            additional_links:
                - title: InscribeDeeper/Job-Descrpition-Feature-extraction
                  icon: fab fa-github
                  url: https://github.com/InscribeDeeper/Job-Descrpition-Feature-extraction
            quote: >
                Short overview of the project (optional)
            description: | # this will include new lines to allow paragraphs
                - Scraped, cleaned and structured Job Descriptions textual data from INDEED.com
                - Filtered noisy data by selecting clusters from K-means algorithm and visualized skillsets distribution
                - Categorized, analyzed skillsets trend after Topic Modeling and Aspect Extraction Deep Neural Network

          - layout: right
            title: Analysis on Factors Influencing Bitcoin
            link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
            link_text: InscribeDeeper/Tweets_sentiment_extraction
            additional_links:
                - title: InscribeDeeper/Tweets_sentiment_extraction
                  icon: fab fa-github
                  url: https://github.com/InscribeDeeper/Tweets_sentiment_extraction
                - title: InscribeDeeper/Time-Series-BTC
                  icon: fab fa-github
                  url: https://github.com/InscribeDeeper/Time-Series-BTC
            quote: >
                Short overview of the project (optional)
            description: | # this will include new lines to allow paragraphs
                - Performed data cleaning and sentiment analysis for over 20 million related Tweets in second granularity
                - Delivered feature engineering for financial indicators like MACD and RSI etc
                - Analyzed, finetuned, and back-tested for over five types of deep learning model to increase the portfolio return

    - title: Education
      layout: list
      content:
          - layout: top-right
            title: Stevens Institute of Technology
            sub_title: MSc in Data Science (GPA 3.8/4.0) # (eg. BA Performing Arts)
            caption: September 2019 - December 2021
            description: | # this will include new lines to allow paragraphs
                Relevant Coursework: Statistical Methods, Statistical Inference, Advanced Data Analytics & Machine Learning, Deep Learning, Natural Language Processing, Database Management Systems, Web Programming, Data Structures & Algorithms

          - layout: top-right
            title: Guangzhou University
            sub_title: BSc in Applied Mathematics # (eg. BA Performing Arts)
            caption: September 2014 - December 2018
            description: | # this will include new lines to allow paragraphs
                Relevant Coursework: Probability and Mathematical Statistics, Operational Research, Numerical Analysis, Advanced Algebra, Mathematical Analysis, Real Function Theory, Functional analysis, Ordinary Differential Equations, Partial Differential Equations

    - title: A Little More About Me
      layout: text
      content: | # this will include new lines to allow paragraphs
          This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

          Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
    sass_dir: _sass
    style: compressed

plugins:
    - jekyll-seo-tag

exclude:
    ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "lib/", "scripts/", "docker-compose.yml"]
